<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <parent>
        <groupId>com.fiap.bank</groupId>
        <artifactId>fiap-bank-atm</artifactId>
        <version>1.0-SNAPSHOT</version>
    </parent>

    <artifactId>fiap-bank-atm-presentation</artifactId>
    <packaging>jar</packaging>
    <name>fiap-bank-atm-presentation</name>

    <dependencies>
        <dependency>
            <groupId>com.fiap.bank</groupId>
            <artifactId>fiap-bank-atm-application</artifactId>
        </dependency>
        <dependency>
            <groupId>com.formdev</groupId>
            <artifactId>flatlaf</artifactId>
        </dependency>
    </dependencies>
</project>
